
# Text Classification using LSTM

This Code Template is for Text Classification using Long short-term memory in python

### Required Packages

In [41]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
import nltk
import re
from nltk.corpus import stopwords
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
pip install tensorflow==2.1.0

### Initialization

Filepath of CSV file

In [43]:
df=pd.read_csv('/content/train.csv')

### Data Fetching

Pandas is an open-source, BSD-licensed library providing high-performance, easy-to-use data manipulation and data analysis tools.

We will use panda's library to read the CSV file using its storage path.And we use the head function to display the initial row or entry.

In [44]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [45]:
###Drop Nan Values
df=df.dropna()


In [46]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [47]:
## Get the Dependent features
y=df['label']

In [48]:
X.shape

(18285, 4)

In [49]:
y.shape

(18285,)

In [50]:
tf.__version__

'2.1.0'

In [51]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [52]:
messages=X.copy()

In [53]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [54]:
messages.reset_index(inplace=True)

In [55]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Data Preprocessing

Since the majority of the machine learning models in the Sklearn library doesn't handle string category data and Null value, we have to explicitly remove or replace null values. The below snippet have functions, which removes the null value if any exists. And convert the string classes data in the datasets by encoding them to integer classes.

In [56]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [57]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [58]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[3956, 2503, 3228, 2898, 494, 523, 2766, 989, 499, 4087],
 [4048, 3150, 857, 847, 2520, 724, 1463],
 [822, 2887, 44, 212],
 [1556, 351, 4645, 348, 441, 3023],
 [3297, 2520, 2054, 4374, 1904, 190, 2520, 2676, 4444, 4216],
 [1266,
  4711,
  1689,
  2630,
  3913,
  4591,
  4505,
  753,
  2828,
  2584,
  4631,
  3937,
  2936,
  3024,
  1463],
 [1480, 1082, 1338, 2537, 4495, 2063, 3783, 944, 2527, 1913, 428],
 [1883, 2370, 3059, 1213, 3102, 4906, 4591, 2923, 2527, 1913, 428],
 [669, 2901, 2169, 3539, 1485, 2922, 858, 3436, 4591, 1014],
 [918, 1326, 1996, 1988, 923, 2657, 2574, 4113],
 [590, 2957, 510, 4668, 191, 1190, 4962, 1149, 1926, 4952, 3282],
 [348, 1254, 494, 2922, 4591, 3102],
 [4026, 2282, 3831, 1977, 1791, 1419, 2715, 2493, 366],
 [2708, 2278, 2441, 1381, 4659, 2471, 4066, 2527, 1913, 428],
 [3736, 2399, 2788, 1556, 2173, 2527, 1913, 428],
 [1843, 3766, 2845, 1930, 3308, 4396, 176, 3398, 1905, 682],
 [4482, 2412, 3150],
 [3576, 4846, 2581, 3809, 4591, 2947, 2786, 1463],
 [1008, 1

### Embedding Representation

In [59]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  989  499 4087]
 [   0    0    0 ... 2520  724 1463]
 [   0    0    0 ... 2887   44  212]
 ...
 [   0    0    0 ... 2527 1913  428]
 [   0    0    0 ... 4489 2754 3220]
 [   0    0    0 ... 1442 2626 2044]]


In [60]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3956,
       2503, 3228, 2898,  494,  523, 2766,  989,  499, 4087], dtype=int32)

### Model
#LSTM
The LSTM model will learn a function that maps a sequence of past observations as input to an output observation. As such, the sequence of observations must be transformed into multiple examples from which the LSTM can learn.

Refer [API](https://towardsdatascience.com/illustrated-guide-to-lstms-and-gru-s-a-step-by-step-explanation-44e9eb85bf21) for the parameters

In [61]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [62]:
len(embedded_docs),y.shape

(18285, (18285,))

In [63]:

X_final=np.array(embedded_docs)
y_final=np.array(y)

In [64]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [65]:

X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [66]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Train on 12250 samples, validate on 6035 samples
Epoch 1/10
12250/12250 [==============================] - 11s 888us/sample - loss: 0.3411 - accuracy: 0.8374 - val_loss: 0.1949 - val_accuracy: 0.9183
Epoch 2/10
12250/12250 [==============================] - 8s 682us/sample - loss: 0.1381 - accuracy: 0.9470 - val_loss: 0.2002 - val_accuracy: 0.9218
Epoch 3/10
12250/12250 [==============================] - 8s 691us/sample - loss: 0.0976 - accuracy: 0.9634 - val_loss: 0.2172 - val_accuracy: 0.9173
Epoch 4/10
12250/12250 [==============================] - 8s 690us/sample - loss: 0.0731 - accuracy: 0.9743 - val_loss: 0.2598 - val_accuracy: 0.9147
Epoch 5/10
12250/12250 [==============================] - 9s 705us/sample - loss: 0.0546 - accuracy: 0.9813 - val_loss: 0.2847 - val_accuracy: 0.9051
Epoch 6/10
12250/12250 [==============================] - 8s 694us/sample - loss: 0.0448 - accuracy: 0.9847 - val_loss: 0.2986 - val_accuracy: 0.9112
Epoch 7/10
12250/12250 [==========================

### Performance Metrics And Accuracy

In [67]:
y_pred=model.predict_classes(X_test)

In [68]:
confusion_matrix(y_test,y_pred)

array([[3123,  296],
       [ 274, 2342]])

## Model Accuracy

In [69]:

accuracy_score(y_test,y_pred)

0.9055509527754764

#### Creator: Ageer Harikrishna , Github: [Profile](https://github.com/ageerHarikrishna)